### ISSUE TITLE
Style: Redesigning the Website Forms

### ISSUE THREAD

**Issue by MonalikaPatnaik** [MonalikaPatnaik/SheEARNS#1]
**What's the style idea?**
Redesigning the forms (for creating a new store and adding an item to your shop of the website), matching with the current theme.

**Add Screenshots**

***Creating a Store***
![Screenshot 2023-11-26 022341](https://github.com/MonalikaPatnaik/SheEARNS/assets/99353300/111cf647-f4b0-4eb3-ab7f-0c7653a4a35c)

***Adding item to the shop***
![image](https://github.com/MonalikaPatnaik/SheEARNS/assets/99353300/6cb3a4da-5158-403f-8a61-e822ae78f74b)

**Comment by aindree-2005** [comment]
@MonalikaPatnaik  can I work on this issue?

**Comment by MonalikaPatnaik** [comment]
Yes @aindree-2005 sure!

**Comment by aindree-2005** [comment]
![Screenshot (217)](https://github.com/MonalikaPatnaik/SheEARNS/assets/68018372/61dfdb31-2158-4173-befb-8b7617e54d5a)
These are the changes I have made till now. Are they ok?
