### ISSUE TITLE
Style: Redesigning the User Profile page

### ISSUE THREAD

**Issue by MonalikaPatnaik** [MonalikaPatnaik/SheEARNS#11]
**What's the style idea?**

The user profile page lacks responsiveness and looks less appealing, redesign the page to make it look good and pleasant.

**Add Screenshots**

![image](https://github.com/MonalikaPatnaik/SheEARNS/assets/99353300/903a2dc4-4d66-4b04-9f40-c1d87d4f32cc)

**Comment by aindree-2005** [comment]
@MonalikaPatnaik can I work on the redesigning? I can make it in sync with the forms design

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik can I work on the redesigning? I can make it in sync with the forms design

Hi, I would suggest you to complete your pending issues first then only take this up.
Thanks!

**Comment by pooranjoyb** [comment]
I'd like to take up this issue under `codepeak 2023`

Assign this to me :) @MonalikaPatnaik
