### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by Tanmay-Joshi73** [MonalikaPatnaik/SheEARNS#15]
![image](https://github.com/MonalikaPatnaik/SheEARNS/assets/124510117/d828c795-cb91-4dfe-a47a-93ff793b1fe7)

> Hey here at the bottom left there are logos (facebook ,github ,instagram ) but they are rediecting to the same page 
> we should provide them some appropriate links
Can u Assign me to this issue ?

**Comment by MonalikaPatnaik** [comment]
Hi, as of now there is only github link only so I'll add it.
You can create other issues related to UI/UX etc. So, closing this.
Thankyou!
