### ISSUE TITLE
Concurretnly open Browser

### ISSUE THREAD

**Issue by Tanmay-Joshi73** [MonalikaPatnaik/SheEARNS#16]
> _Hey I would like to add a new functionality that whenever we  run npm start it will automatically start the nodemon sevver and browse for us we dont have  to manually open it from the browser and it will automatically start server and open brower wit the specified route 

> for that i am using concurrently and open browse package on npm_

**Comment by MonalikaPatnaik** [comment]
Hi @Tanmay-Joshi73, I don't think it's in a priority right now.
