### ISSUE TITLE
Feat: Business Logo

### ISSUE THREAD

**Issue by aindree-2005** [MonalikaPatnaik/SheEARNS#17]
**Describe the feature.**

The SheEarns website doesn't have a logo. I intend to design a logo on Illustrator for She Earns and redesign the alignment of the navbar to include the logo
**Add Screenshots**

![Screenshot (236)](https://github.com/MonalikaPatnaik/SheEARNS/assets/68018372/8025858f-95c4-4ef5-a838-b136f338b2fb)

**Comment by aindree-2005** [comment]
![She Earns](https://github.com/MonalikaPatnaik/SheEARNS/assets/68018372/8647e7b3-dc2c-4465-9bb1-73566e17815b)
@MonalikaPatnaik is this logo ok?

**Comment by MonalikaPatnaik** [comment]
Hi, there should be no gap between she and earns. The logo is okay just a change in color to pink is recommended.

**Comment by aindree-2005** [comment]
> Hi, there should be no gap between she and earns. The logo is okay just a change in color to pink is recommended.

Got it! Will make the changes ASAP
