### ISSUE TITLE
BUG:Adding Email Validtion for Sign Up for Newsletter 

### ISSUE THREAD

**Issue by Ayusht777** [MonalikaPatnaik/SheEARNS#26]
**Describe the bug**
It doesn't have any check for email is enter is valid or not

**Expected behavior**
Should Have A Error Message Showing that email is not correct 

**Screenshots**
![image](https://github.com/MonalikaPatnaik/SheEARNS/assets/106388215/abd045e8-eb16-494f-9731-a1b84f7517e6)

**Comment by Yash-Ainapure** [comment]
@MonalikaPatnaik , I would like to take this issue up. Please assign it to me
