### ISSUE TITLE
Enhancing Navbar for Homepage and shop box

### ISSUE THREAD

**Issue by PSS2134** [MonalikaPatnaik/SheEARNS#27]
I wish to change the ui of the navbar like alignment of the elements of navbar and 
Also shops shown into a card like structure with shop image on top and its description below with view shop button below and make cards three in a row
@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Hi, you can work on enhancing the navbar of the site.
Thankyou!

**Comment by PSS2134** [comment]
I have created a PR #33  @MonalikaPatnaik
