### ISSUE TITLE
Need for proper documentation 

### ISSUE THREAD

**Issue by deveshio** [MonalikaPatnaik/SheEARNS#3]
I'd like to add a contribution.md file to guide contributors as this is an open-source project 
and keeping a separate readme.Md file for explaining the project

**Comment by deveshio** [comment]
I'd like to work on this issue

**Comment by MonalikaPatnaik** [comment]
Hey @Devesh-Daku, thanks for suggesting, I'll add it. Meanwhile I suggest you to open issues related to bug, feature or styling of the website..
Thanks!

**Comment by deveshio** [comment]
Sure
