### ISSUE TITLE
Change Contact us Form design

### ISSUE THREAD

**Issue by PSS2134** [MonalikaPatnaik/SheEARNS#34]
**What's the style idea?**
![Screenshot 2023-12-22 025239](https://github.com/MonalikaPatnaik/SheEARNS/assets/101321904/43a90f1c-f7a1-48ce-a850-b00855c89ae8)

**Comment by MonalikaPatnaik** [comment]
Hi @PSS2134, i think contact page design is looking fine and there is no need to change it.
