### ISSUE TITLE
New Profile Page with profile image upload feature

### ISSUE THREAD

**Issue by PSS2134** [MonalikaPatnaik/SheEARNS#36]
1.A brief description of user which he can edit
2. see his shops
3. Orders ( in future )

**Comment by MonalikaPatnaik** [comment]
Hi, refer to my comment on https://github.com/MonalikaPatnaik/SheEARNS/pull/19#issuecomment-1850782643

**Comment by MonalikaPatnaik** [comment]
Closing the issue!`
