### ISSUE TITLE
Feat: Add Routing for footer (About, Contact, Faq)

### ISSUE THREAD

**Issue by AaadityaG** [MonalikaPatnaik/SheEARNS#37]
There is no action for footer links

**Comment by AaadityaG** [comment]
@MonalikaPatnaik Please asign this to me

**Comment by MonalikaPatnaik** [comment]
Okay, you can design a faq page and link to that in the footer. Rest about and contact page is there, you have to just link it in footer.

**Comment by AaadityaG** [comment]
Do you have some of ques and answers for faq... Or I should use lorem30 for answers

**Comment by MonalikaPatnaik** [comment]
You can use some random text, will change it according to the need

**Comment by AaadityaG** [comment]
ok
