### ISSUE TITLE
Feat: 404 page missing

### ISSUE THREAD

**Issue by Yash-Ainapure** [MonalikaPatnaik/SheEARNS#44]
I would like to add a "404 page not found" page . If the redirect url is not present then this page will be shown instead of showing errors on page which is not good for user experience
@MonalikaPatnaik 
the page i am talking about will look like this :

![Screenshot (127)](https://github.com/MonalikaPatnaik/SheEARNS/assets/136250383/2a06642b-6753-490b-9fba-5971b2f75798)

**Comment by MonalikaPatnaik** [comment]
It's been done by #28
