### ISSUE TITLE
BUG: Quick links

### ISSUE THREAD

**Issue by AaadityaG** [MonalikaPatnaik/SheEARNS#55]
Make footer quick link pages for all four elements 

Add them a routing 

Please allow me to work on it under codepeak

**Comment by AaadityaG** [comment]
@MonalikaPatnaik Please add kwoc tag..

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik Please add kwoc tag..

https://github.com/MonalikaPatnaik/SheEARNS/pull/68#issuecomment-1878748685

**Comment by AaadityaG** [comment]
Pehele batana tha na..😂 anyways..its ok.😅
