### ISSUE TITLE
Style: Fixing contact page 

### ISSUE THREAD

**Issue by Yash-Ainapure** [MonalikaPatnaik/SheEARNS#60]
Improper style for contact page

Changes i will make:
* make proper contact page 

![Screenshot (156)](https://github.com/MonalikaPatnaik/SheEARNS/assets/136250383/60ba8284-2aa9-4327-bcab-bd7cfac14a7c)

**Comment by Yash-Ainapure** [comment]
@MonalikaPatnaik , I didn't get the points for the issues i created

**Comment by MonalikaPatnaik** [comment]
Hi, I have given you collective 30 points. Consider this points for both your pr and issue since the time is over and I was not able to give you points for the issues

**Comment by Yash-Ainapure** [comment]
> Hi, I have given you collective 30 points. Consider this points for both your pr and issue since the time is over and I was not able to give you points for the issues

But i just got 1point back of 10th position, so i tried to ask for the points 🙂. If you could try giving pts for the issue it would be great . 
Anyway, if it's not possible then ok

**Comment by MonalikaPatnaik** [comment]
> > Hi, I have given you collective 30 points. Consider this points for both your pr and issue since the time is over and I was not able to give you points for the issues
> 
> But i just got 1point back of 10th position, so i tried to ask for the points 🙂. If you could try giving pts for the issue it would be great . Anyway, if it's not possible then ok

Hi, okay I'm trying
