### ISSUE TITLE
BUG:Absence of Form Validation on Website

### ISSUE THREAD

**Issue by Ayusht777** [MonalikaPatnaik/SheEARNS#7]
**Describe the bug**
it allows users to submit entries without proper phone number numeric validation and permits empty or incorrectly formatted email entries. 

**Expected behavior**
The website should enforce proper validation checks for phone numbers, ensuring only numeric entries are accepted. Additionally, email fields should have validation to prevent submission of empty or incorrectly formatted email addresses. This would enhance data accuracy and user input integrity.

**Screenshots**

**Comment by MonalikaPatnaik** [comment]
Hi, could you tell me which form are you talking about? There is no form which accepts users' phone number.
